name: Deploy to Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Composer Dependencies
        run: composer require tightenco/jigsaw --no-interaction --no-progress
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Production
        run: npm run prod
      - name: Deploy to Production
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_DOMAIN }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build_production
