name: Deploy to Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Imagemagick
        run: sudo apt install imagemagick
      - name: Install composer
        uses: php-actions/composer@v2
        with:
          command: require tightenco/jigsaw
      - name: Setup Node version 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm ls
      - run: npm run prod
      - name: Deploy to production
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_DOMAIN }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build_production
