name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@master
      - name: Composer install
        uses: docker://composer:1.10.8
        with:
          args: install
      - name: Composer require Jigsaw
        uses: docker://php:7.4
        with:
          args: composer require tightenco/jigsaw
      - name: Setup Node version 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm install
      - run: npm run production
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          # Formatted as protocol://domain.com:port/full/destination/path/
          ftp-server: ${{ secrets.FTP_DIR }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build_production
