name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: php-actions/composer@v2
        with:
          args: composer require tightenco/jigsaw
      - name: Setup Node version 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm install
      - run: npm run production
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_DOMAIN }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build_production
