name: Deploy to IBM Cloud Storage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Imagemagick
        run: sudo apt install imagemagick
      - name: Install Composer
        uses: php-actions/composer@v2
        with:
          command: require tightenco/jigsaw
      - name: Setup Node version 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install all modules
        run: npm install
      - name: Produce production build
        run: npm run production
      - name: Minio deploy to IBM
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: static-portfolio
          source_dir: build_production/
          target_dir: /
